# Generated by Django 4.1.2 on 2022-12-03 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_number', models.CharField(max_length=64, verbose_name='教职工号')),
                ('teacher_name', models.CharField(max_length=32, unique=True, verbose_name='教师姓名')),
                ('teacher_gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('teacher_age', models.IntegerField(verbose_name='年龄')),
                ('teacher_birth', models.DateField(verbose_name='出生年月')),
                ('teacher_phone', models.CharField(max_length=64, verbose_name='联系电话')),
                ('teacher_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department', verbose_name='所属院系')),
            ],
        ),
    ]
