# Generated by Django 4.1.2 on 2022-12-03 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=64, verbose_name='课程代码')),
                ('course_name', models.CharField(max_length=255, verbose_name='课程名字')),
                ('course_type', models.SmallIntegerField(choices=[(1, '必修'), (2, '选修')], verbose_name='是否为选修')),
                ('course_credit', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='学分')),
                ('course_major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.major', verbose_name='所属专业')),
            ],
        ),
    ]
