# Generated by Django 4.1.2 on 2022-12-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=64, verbose_name='班级ID')),
                ('class_name', models.CharField(max_length=255, verbose_name='班级名称')),
                ('class_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department', verbose_name='所属院系')),
                ('class_major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.major', verbose_name='所属专业')),
            ],
        ),
    ]
