# Generated by Django 4.1.2 on 2022-12-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_classinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField(verbose_name='学号')),
                ('student_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('student_gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('student_birth', models.DateField(verbose_name='出生年月')),
                ('student_scores', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='学生总成绩')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.classinfo', verbose_name='所属班级')),
                ('student_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department', verbose_name='所属院系')),
                ('student_major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.major', verbose_name='所属专业')),
            ],
        ),
    ]
