# Generated by Django 4.1.2 on 2022-12-03 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_studentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='student_number',
            field=models.IntegerField(max_length=64, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='teacher_name',
            field=models.CharField(max_length=32, verbose_name='教师姓名'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='teacher_number',
            field=models.CharField(max_length=64, unique=True, verbose_name='教职工号'),
        ),
        migrations.CreateModel(
            name='TeacherLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_passwd', models.CharField(max_length=64, verbose_name='登录密码')),
                ('login_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacherinfo', to_field='teacher_number', verbose_name='登录名')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_passwd', models.CharField(max_length=64, verbose_name='登录密码')),
                ('login_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentinfo', to_field='student_number', verbose_name='登录名')),
            ],
        ),
    ]
