# Generated by Django 4.1.2 on 2022-12-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_studentinfo_student_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='student_number',
            field=models.CharField(max_length=64, unique=True, verbose_name='学号'),
        ),
    ]
