# Generated by Django 4.1.2 on 2022-12-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_studentinfo_student_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherlogin',
            name='login_username',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='login_passwd',
            field=models.CharField(default=123, max_length=64, verbose_name='登录密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='login_passwd',
            field=models.CharField(default=123, max_length=64, verbose_name='登录密码'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StudentLogin',
        ),
        migrations.DeleteModel(
            name='TeacherLogin',
        ),
    ]
