# Generated by Django 4.1.2 on 2022-12-04 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_teacherlogin_login_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='login_passwd',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='login_passwd',
        ),
        migrations.CreateModel(
            name='TeacherLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_passwd', models.CharField(max_length=64, verbose_name='登录密码')),
                ('login_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacherinfo', to_field='teacher_number', verbose_name='登录名')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_passwd', models.CharField(max_length=64, verbose_name='登录密码')),
                ('login_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentinfo', to_field='student_number', verbose_name='登录名')),
            ],
        ),
    ]
