# Generated by Django 4.1.2 on 2022-12-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_studentinfo_login_passwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='student_scores',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='学生总成绩'),
        ),
    ]
