# Generated by Django 4.1.2 on 2022-12-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_teacherlogin_login_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_type',
            field=models.SmallIntegerField(choices=[(1, '必修'), (2, '选修')], verbose_name='是否必修'),
        ),
    ]
