# Generated by Django 4.1.2 on 2022-12-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_courses_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_type',
            field=models.CharField(max_length=20, verbose_name='是否必修'),
        ),
    ]
