# Generated by Django 4.1.2 on 2022-12-14 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_courses_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='class_id',
            field=models.CharField(max_length=60, verbose_name='班级ID'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='课程名字'),
        ),
        migrations.CreateModel(
            name='ChoiceCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=64, verbose_name='学号')),
                ('student_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('course_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.courses', to_field='course_name', unique=True, verbose_name='课程名称')),
            ],
        ),
    ]
