# Generated by Django 4.1.2 on 2022-12-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_classinfo_class_id_alter_courses_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicecourse',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.studentinfo', verbose_name='id'),
        ),
    ]
