# Generated by Django 4.1.2 on 2022-12-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_choicecourse_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicecourse',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.courses', to_field='course_name', verbose_name='课程名称'),
        ),
    ]
