# Generated by Django 4.1.2 on 2022-12-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_choicecourse_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicecourse',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.courses', verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=255, verbose_name='课程名字'),
        ),
    ]
